### ISSUE TITLE
خطا توی بعضی اکانت ها

### ISSUE THREAD

**Issue by alighafoori** [behrouzbakhtiari/twitter-word-cloud#3]
دستور اجرا شده 
python twc.py soboutipour 200

Traceback (most recent call last):
  File "twc.py", line 141, in <module>
    main()
  File "twc.py", line 137, in main
    generate_word_cloud()
  File "twc.py", line 114, in generate_word_cloud
    data['clean_tweet'] = data['tweet'].apply(lambda x: clean_tweet(x))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2327, in pandas._libs.lib.map_infer
  File "twc.py", line 114, in <lambda>
    data['clean_tweet'] = data['tweet'].apply(lambda x: clean_tweet(x))
  File "twc.py", line 69, in clean_tweet
    tweet = tweet.lower()
AttributeError: 'float' object has no attribute 'lower'

**Comment by behrouzbakhtiari** [comment]
این خطا رفع شد و رپو آپدیت شد

**Comment by ahangarha** [comment]
CLOSE please
